name: Build Docker image

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
          
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          tags: kedoodle/reveal-docker:latest
