name: Publish presentation to GitHub Pages

on:
  push:
    # branches:
    #   - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      
      - name: ":ship: Build the docker-compose service"
        run: docker-compose up -d serve
      
      - name: ":file_folder: Copy presentation files"
        run: docker cp reveal-docker_serve_1:/reveal.js .
      
      - name: ":rocket: Deploy to GitHub Pages"
        uses: JamesIves/github-pages-deploy-action@4.1.1
          with:
            branch: gh-pages
            folder: reveal.js
