name: Publish example presentation to GitHub Pages

on:
  workflow_run:
    workflows:
      - Build and push Docker image
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run presentation
        run: |
          docker run --rm --name reveal-docker \
            -p 8000:8000 \
            -v "$(pwd)"/src/index.html:/reveal.js/index.html \
            -v "$(pwd)"/src/slides.md:/reveal.js/slides.md \
            kedoodle/reveal-docker:latest
      
      - name: Copy presentation files
        run: docker cp reveal-docker:/reveal.js .
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: reveal.js
